
<?php 
  $customerId = $this->getRequest()->getParam('id');
  $customerInfo = Mage::getModel('customerdetails/extendedinfo')->load($customerId, 'entity_id');
  
  $matric_year = array();
  for ($i=1991; $i <= 2021; $i++) { 
      if($i == $customerInfo->getMatriculationYear())
        $matric_year[] = '<option selected value="'.$i.'">'.$i.'</option>';
      $matric_year[] = '<option value="'.$i.'">'.$i.'</option>';
  }

  $intermediate_year = array();
  for ($i=1991; $i <= 2021; $i++) { 
      if($i == $customerInfo->getIntermediateYear())
        $intermediate_year[] = '<option selected value="'.$i.'">'.$i.'</option>';
      $intermediate_year[] = '<option value="'.$i.'">'.$i.'</option>';
  }

  $graduation_year = array();
  for ($i=1991; $i <= 2021; $i++) { 
      if($i == $customerInfo->getGraduationYear())
        $graduation_year[] = '<option selected value="'.$i.'">'.$i.'</option>';
      $graduation_year[] = '<option value="'.$i.'">'.$i.'</option>';
  }

  $pgraduation_year = array();
  for ($i=1991; $i <= 2021; $i++) { 
      if($i == $customerInfo->getPgraduationYear())
        $pgraduation_year[] = '<option selected value="'.$i.'">'.$i.'</option>';
      $pgraduation_year[] = '<option value="'.$i.'">'.$i.'</option>';
  }
 ?>


<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
<input type="hidden" name="entity_id" id="entity_id" value="<?php echo $customerId; ?>" />
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Matriculation Information</h4>
    <div class="form-buttons"></div>
</div>
<div class="fieldset">
    <table class="form-list" cellspacing="0">
    <tbody>
        <tr>
        	<td class="label">
            	<label for="matriculation_year"><?php echo $this->__('Matriculation Year') ?> <span class="required">*</span></label>
            </td>
            <td class="value">
                <div class="input-box">
                    <select style="" class="validate-select required-entry" title="Matriculation Year" name="bk[matriculation_year]" id="matriculation_year" defaultvalue="0">
                           <option value="">Please select year of completion</option>
                           <?php
                              foreach ($matric_year as $options) {
                                echo $options;
                              }
                           ?>
                    </select>
                </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        		<label for="matriculation_school"><?php echo $this->__('School') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
	            <div>
	            	<input type="text" name="bk[matriculation_school]" id="matriculation_school" value="<?php echo $customerInfo->getMatriculationSchool() ?>" title="<?php echo $this->__('Matriculation School') ?>" class="input-text required-entry" />
	            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        		<label for="matriculation_city"><?php echo $this->__('City') ?> <span class="required">*</span></label>
    		</td>
    		<td class="value">
	            <div>
	            	<input type="text" name="bk[matriculation_city]" id="matriculation_city" value="<?php echo $customerInfo->getMatriculationCity() ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" />
	            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        		<label for="matriculation_stream"><?php echo $this->__('Stream') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
	            <div>
	            	<input type="text" name="bk[matriculation_stream]" id="matriculation_stream" value="<?php echo $customerInfo->getMatriculationStream() ?>" title="<?php echo $this->__('Stream') ?>" class="input-text required-entry" />
	            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        		<label for="matriculation_marks"><?php echo $this->__('Marks/Grade') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
	            <div>
	            	<input type="text" name="bk[matriculation_marks]" id="matriculation_marks" value="<?php echo $customerInfo->getMatriculationMarks() ?>" title="<?php echo $this->__('Marks/Grade') ?>" class="input-text required-entry" />
	            </div>
            </td>
        </tr>
    </tbody>
    </table>
</div>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Intermediate Information</h4>
    <div class="form-buttons"></div>
</div>
<div class="fieldset">
    <table class="form-list" cellspacing="0">
        <tr>
        	<td class="label">
            <label for="intermediate_year"><?php echo $this->__('Intermediate Year') ?> <span class="required">*</span></label>
            </td>
            <td class="value">
            <div class="input-box">
                <select style="" class="validate-select required-entry" title="Intermediate Year" name="bk[intermediate_year]" id="intermediate_year" defaultvalue="0">
                       <option value="">Please select year of completion</option>
                       <?php
                          foreach ($intermediate_year as $options) {
                            echo $options;
                          }
                       ?>
                </select>
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="intermediate_school"><?php echo $this->__('School/Institute') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[intermediate_school]" id="intermediate_school" value="<?php echo $customerInfo->getIntermediateSchool() ?>" title="<?php echo $this->__('Intermediate Institute') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="intermediate_city"><?php echo $this->__('City') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[intermediate_city]" id="intermediate_city" value="<?php echo $customerInfo->getIntermediateCity() ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="intermediate_stream"><?php echo $this->__('Stream') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[intermediate_stream]" id="intermediate_stream" value="<?php echo $customerInfo->getIntermediateStream() ?>" title="<?php echo $this->__('Stream') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="intermediate_marks"><?php echo $this->__('Marks/Grade') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[intermediate_marks]" id="intermediate_marks" value="<?php echo $customerInfo->getIntermediateMarks() ?>" title="<?php echo $this->__('Marks/Grade') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Graduation Information</h4>
    <div class="form-buttons"></div>
</div>
<div class="fieldset">
    <table class="form-list" cellspacing="0">
        <tr>
        	<td class="label">
            <label for="graduation_year"><?php echo $this->__('Graduation Year') ?> <span class="required">*</span></label>
            </td>
            <td class="value">
            <div class="input-box">
                <select style="" class="validate-select required-entry" title="Graduation Year" name="bk[graduation_year]" id="graduation_year" defaultvalue="0">
                       <option value="">Please select year of completion</option>
                       <?php
                          foreach ($graduation_year as $options) {
                            echo $options;
                          }
                       ?>
                </select>
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="graduation_institute"><?php echo $this->__('Graduation College') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[graduation_college]" id="graduation_college" value="<?php echo $customerInfo->getGraduationCollege() ?>" title="<?php echo $this->__('Graduation College') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="graduation_university"><?php echo $this->__('Graduation University') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[graduation_university]" id="graduation_university" value="<?php echo $customerInfo->getGraduationUniversity() ?>" title="<?php echo $this->__('Graduation University') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="graduation_city"><?php echo $this->__('City') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[graduation_city]" id="graduation_city" value="<?php echo $customerInfo->getGraduationCity() ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="graduation_stream"><?php echo $this->__('Stream') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[graduation_stream]" id="graduation_stream" value="<?php echo $customerInfo->getGraduationStream() ?>" title="<?php echo $this->__('Stream') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="graduation_marks"><?php echo $this->__('Marks/Grade') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[graduation_marks]" id="graduation_marks" value="<?php echo $customerInfo->getGraduationMarks() ?>" title="<?php echo $this->__('Marks/Grade') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Post Graduation Information</h4>
    <div class="form-buttons"></div>
</div>
<div class="fieldset">
    <table class="form-list" cellspacing="0">
        <tr>
        	<td class="label">
            <label for="pgraduation_year"><?php echo $this->__('Post Graduation Year') ?> <span class="required">*</span></label>
            </td>
            <td class="value">
            <div class="input-box">
                <select style="" class="validate-select required-entry" title="Post Graduation Year" name="bk[pgraduation_year]" id="pgraduation_year" defaultvalue="0">
                       <option value="">Please select year of completion</option>
                       <?php
                          foreach ($pgraduation_year as $options) {
                            echo $options;
                          }
                       ?>
                </select>
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="pgraduation_institute"><?php echo $this->__('Post Graduation College') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[pgraduation_college]" id="pgraduation_college" value="<?php echo $customerInfo->getPgraduationCollege() ?>" title="<?php echo $this->__('Post Graduation College/Institute') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="pgraduation_university"><?php echo $this->__('Post Graduation University') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[pgraduation_university]" id="pgraduation_university" value="<?php echo $customerInfo->getPgraduationUniversity() ?>" title="<?php echo $this->__('PostGraduation University') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="pgraduation_city"><?php echo $this->__('City') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[pgraduation_city]" id="pgraduation_city" value="<?php echo $customerInfo->getPgraduationCity() ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="pgraduation_stream"><?php echo $this->__('Stream') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[pgraduation_stream]" id="pgraduation_stream" value="<?php echo $customerInfo->getPgraduationStream() ?>" title="<?php echo $this->__('Stream') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
        <tr>
        	<td class="label">
        	<label for="pgraduation_marks"><?php echo $this->__('Marks/Grade') ?> <span class="required">*</span></label>
        	</td>
        	<td class="value">
            <div>
            	<input type="text" name="bk[pgraduation_marks]" id="pgraduation_marks" value="<?php echo $customerInfo->getPgraduationMarks() ?>" title="<?php echo $this->__('Marks/Grade') ?>" class="input-text required-entry" />
            </div>
            </td>
        </tr>
    </table>
</div>
